# Site settings
name: michael the Cycle
email: mjbvegeta@yeah.net
author: Vegeta Michael
url: https://vegetamichael.github.io/
resume_site: https://vegetamichael.github.io/
github: https://github.com/vegetaMICHAEL
baseurl: ""
description: Enjoy hardships of life
meta_description: vegeta;Blog;Just do it
motto: Enjoy yourself
banner: Stay hungry, stay foolish

permalink: /:categories/:year/:month/:day/:title/
#permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: vegetaMICHAEL

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

